version: '3.5'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    privileged: true
    restart: always
    ports:
      - 20080:80
      - 20443:443
    volumes:
      - /var/lib/docker/volumes/nextcloud:/var/www/html
