version: '3.5'
services:
  nextcloud:
    image: nextcloud:fpm
    container_name: nextcloud
    privileged: true
    restart: always
    links:
      - mysql:mysql
    volumes:
      - /var/lib/docker/volumes/nextcloud:/var/www/html
    networks:
      nextcloud_network:
        ipv4_address: 172.24.0.2
  nextcloud_nginx:
    image: nginx
    container_name: nextcloud_nginx
    privileged: true
    restart: always
    ports:
      - 20080:80
      - 20443:443
    links:
      - mysql:mysql
      - nextcloud:nextcloud
    volumes:
      - /var/lib/docker/volumes/nextcloud:/var/www/html
      - nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx/conf.d:/etc/nginx/conf.d
      - nginx/cert:/etc/nginx/cert
    networks:
      nextcloud_network:
        ipv4_address: 172.24.0.3
networks:
  nextcloud_network:
    external: false
    name: nextcloud_network
    ipam:
      config:
      - subnet: 172.24.0.0/24
