version: '3.5'
services:
  haproxy1:
    image: haproxy:latest
    container_name: mysql_pxc_h1
    privileged: true
    restart: always
    ports:
      - 4001:8888
      - 13306:3306
    volumes:
      - ./config/haproxy1:/usr/local/haproxy
    networks:
      mysql_pxc_network:
        ipv4_address: 172.20.0.11
    privileged: true        
    command: haproxy -f /usr/local/haproxy/haproxy.cfg
networks:
  mysql_pxc_network:
    external: false
    name: mysql_pxc_network
    ipam:
      config:
      - subnet: 172.20.0.0/24
